version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # RabbitMQ port
      - "15672:15672"  # Management console port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  service1:
    build: ./service1
    container_name: service1
    ports:
      - "8081:8081"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - microservices-network
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest

  service2:
    build: ./service2
    container_name: service2
    ports:
      - "8082:8082"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - microservices-network
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest

networks:
  microservices-network:
    driver: bridge